#!/usr/bin/env bash
# nginx redirection /redirect_me
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sed -i '/root /var/www/html/a error_page 404 /404.html;                                                                    
        location = /404.html {                                                                       
                root /var/www/error/;                                                               
                internal;                                                                           
        }' /etc/nginx/sites-available/default
service nginx restart