#!/usr/bin/env bash
# Install load balancer HAproxy with version 1.5 or greater; uses roundrobin algorithm
sudo apt-get update
sudo apt-get -y install haproxy
printf "\nfrontend firstbalance\n
\tbind *:80\n
\tmode http\n
\toption forwardfor\n
\tdefault_backend webservers\n\n
backend webservers\n\
\tbalance roundrobin\n
\tserver 1588-web-01 34.75.208.26:80\n
\tserver 1588-web-02 54.147.163.239:80\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start