#!/usr/bin/env bash
# script with the minimum number of commands to automate your fix

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start